version: '3'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper:22888:23888
      ZOOKEEPER_TICK_TIME: 2000

  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka2
    ports:
      - "19092:19092"
      - "39092:39092"
    depends_on:
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper2:32181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:39092,PLAINTEXT_HOST://localhost:19092
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - zookeeper1
      - zookeeper2
    ports:
      - "80:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      - KAFKA_CLUSTERS_1_NAME=kafka2
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka2:39092
      - KAFKA_CLUSTERS_1_ZOOKEEPER=localhost:32181

  kafka-setup:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka-setup
    container_name: kafka1-setup
    depends_on:
      - kafka1
      - kafka2
      - kafka-ui
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    command: sh -c "sleep 20 && kafka-topics --create --if-not-exists --bootstrap-server kafka1:29092 --partitions 1 --replication-factor 1 --topic requests && kafka-topics --create --if-not-exists --bootstrap-server broker1:29092 --partitions 1 --replication-factor 1 --topic status_topic && kafka-topics --create --if-not-exists --bootstrap-server kafka2:39092 --partitions 1 --replication-factor 1 --topic results"

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ROOT
      - POSTGRES_DB=some_service
    ports:
      - "5432:5432"